import { readFile, mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const manifestPath = path.join(root, "claw.manifest.json");
const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
const checkOnly = process.argv.includes("--check");

function luaString(value) {
  return JSON.stringify(value).replaceAll("\\u2028", "\\u{2028}").replaceAll("\\u2029", "\\u{2029}");
}

const chunks = [
  "-- This file is generated by scripts/build.mjs. Do not edit it directly.",
  `-- Project: ${manifest.name}`,
  "",
  "local __clawEnvironment = getgenv and getgenv() or _G",
  "__clawEnvironment.__CLAW_MODULES = {}",
  "",
];

for (const relativePath of manifest.modules) {
  const absolutePath = path.join(root, relativePath);
  const source = await readFile(absolutePath, "utf8");
  chunks.push(`-- BEGIN MODULE: ${relativePath}`);
  chunks.push("do");
  chunks.push(`  local moduleName = ${luaString(relativePath)}`);
  chunks.push("  local moduleFactory = function()");
  const indentedSource = source
    .replace(/\r?\n$/, "")
    .split(/\r?\n/)
    .map((line) => (line.length > 0 ? `\t${line}` : ""))
    .join("\n");
  chunks.push(indentedSource);
  chunks.push("  end");
  chunks.push("  __clawEnvironment.__CLAW_MODULES[moduleName] = moduleFactory()");
  chunks.push("end");
  chunks.push(`-- END MODULE: ${relativePath}`);
  chunks.push("");
}
const entrySource = await readFile(path.join(root, manifest.entry), "utf8");
chunks.push(`-- BEGIN ENTRY: ${manifest.entry}`);
chunks.push(entrySource);
chunks.push(`-- END ENTRY: ${manifest.entry}`);
chunks.push("");

const output = chunks.join("\n");
const outputPath = path.join(root, manifest.output);
const digest = createHash("sha256").update(output).digest("hex");

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch(() => null);
  if (current !== output) {
    console.error(`${manifest.output} is missing or stale. Run npm run build.`);
    process.exitCode = 1;
  } else {
    console.log(`${manifest.output} is current (${digest.slice(0, 12)}).`);
  }
} else {
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
  console.log(`Built ${manifest.output} (${digest.slice(0, 12)}).`);
}
