import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = path => readFileSync(resolve(root, path), 'utf8').replaceAll('\r\n', '\n');
function quote(source) {
  let eq = '='; while (source.includes(']' + eq + ']')) eq += '=';
  return '[' + eq + '[' + source + ']' + eq + ']';
}
const modules = ['join/core.lua', 'control/auto.lua', 'control/regions.lua', 'control/menu-scan.lua', 'control/catalog.lua'];
const client = read('control/client.lua');
const download = 'local source = game:HttpGet(BASE .. path .. "?cache=" .. Http:GenerateGUID(false))';
if (client.split(download).length !== 2) throw Error('Client module loader changed; review bundle generation');
const bundle = '-- Generated by tools/build-control.mjs; edit source modules, not this file.\n'
  + 'local __CLAW_BUNDLE = {\n' + modules.map(path => ` [${JSON.stringify(path)}] = ${quote(read(path))},`).join('\n')
  + '\n}\n' + client.replace(download, 'local source = assert(__CLAW_BUNDLE[path], "Unknown bundled module")');
const pairingMarker = /-- PAIR_MODULE_BEGIN\n[\s\S]*?-- PAIR_MODULE_END/;
const launcherSource = read('control-launcher.lua');
if (!pairingMarker.test(launcherSource)) throw Error('Pairing loader marker changed');
const launcher = launcherSource.replace(pairingMarker, () => 'if getgenv().CLAW_PAIR ~= nil then\nassert(loadstring('
  + quote(read('control/pair.lua')) + ', "@CLAW/pair.lua"))()\nend');
const launchMarker = 'local url = "https://raw.githubusercontent.com/Clawdews/CLAW/control-beta/control-client.lua"';
if (launcher.split(launchMarker).length !== 2) throw Error('Launcher changed; review bundle generation');
const launchBundle = '-- Generated by tools/build-control.mjs; private pairing files are read locally, never embedded.\n'
  + launcher.slice(0, launcher.indexOf(launchMarker))
  + 'return assert(loadstring(' + quote(bundle) + ', "@CLAW/control-beta.lua"))()\n';
const artifacts = { 'control-beta.lua': bundle, 'launcher-beta.lua': launchBundle };
const version = JSON.parse(read('control/package.json')).version;
for (const [path, expected] of Object.entries({
  'control/auto.lua': `VERSION = "${version}"`, 'control/client.lua': `Auto.VERSION == "${version}"`,
  'control/worker.js': `version: '${version}'`,
})) if (!read(path).includes(expected)) throw Error(`Release version mismatch in ${path}`);
const manifest = JSON.stringify({ version, modules,
  artifacts: Object.entries(artifacts).map(([file, source]) => ({ file, bytes: Buffer.byteLength(source),
    sha256: createHash('sha256').update(source).digest('hex') })) }, null, 2) + '\n';
const outputs = { 'dist/control-beta.lua': bundle, 'dist/launcher-beta.lua': launchBundle, 'dist/control-beta.json': manifest };
if (process.argv.includes('--check')) {
  for (const [path, expected] of Object.entries(outputs)) if (read(path) !== expected) throw Error('Rebuild stale artifact: ' + path);
  console.log('Control bundle matches source');
} else {
  mkdirSync(resolve(root, 'dist'), { recursive: true });
  for (const [path, content] of Object.entries(outputs)) writeFileSync(resolve(root, path), content);
  console.log('Built one self-contained control client (' + Buffer.byteLength(bundle) + ' bytes)');
}
